# YOLOv5 ğŸš€ by Ultralytics, GPL-3.0 license
# COCO128 dataset https://www.kaggle.com/ultralytics/coco128 (first 128 images from COCO train2017) by Ultralytics
# Example usage: python train.py --data coco128.yaml
# parent
# â”œâ”€â”€ yolov5
# â””â”€â”€ datasets
#     â””â”€â”€ coco128  â† downloads here (7 MB)


# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /home/mirap/0_DATABASE/ocean_waste/float_sideview/ # dataset root dir
train: train  # train images (relative to 'path') 138 images
val: val # val images (relative to 'path') fold1 - 34 images
test: # test images (optional) 

# Classes
nc: 20 # number of classes
names: ['Glass_bottle',
  'Glass_bulb',
  'Metal',
  'Net_Buoy',
  'Net_Corn',
  'Net_rope',
  'PET_Bottle',
  'Plastic_Bottle',
  'Plastic_Buoy',
  'Plastic_Buoy_Big',
  'Plastic_Buoy_round',
  'Plastic_ETC',
  'Plastic_Square',
  'Rope',
  'Rope_clear',
  'Rope_thin',
  'Styrofoam_Box',
  'Styrofoam_Buoy',
  'Styrofoam_Piece',
  'Vinyl'
]  # class names


# Download script/URL (optional)
# download: https://ultralytics.com/assets/coco128.zip
